// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIOa6YNshdEcXEGS0xaKAEVpBGuG3ag8',
    appId: '1:836951260412:web:8b93627a5236548b69ab79',
    messagingSenderId: '836951260412',
    projectId: 'uwords-2929',
    authDomain: 'uwords-2929.firebaseapp.com',
    storageBucket: 'uwords-2929.appspot.com',
    measurementId: 'G-5X049ZHPEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRsU3doDePNlMBbJFS3SPa8egR9dEJyt8',
    appId: '1:836951260412:android:fabd7185aeeedc0f69ab79',
    messagingSenderId: '836951260412',
    projectId: 'uwords-2929',
    storageBucket: 'uwords-2929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClxy9LE8QYOyE-R5-cI5ekrIhEpdTqq-4',
    appId: '1:836951260412:ios:f11cafbe43ed48eb69ab79',
    messagingSenderId: '836951260412',
    projectId: 'uwords-2929',
    storageBucket: 'uwords-2929.appspot.com',
    androidClientId: '836951260412-d8bmt2i35jnflgjjqrol8r704ilf9bdt.apps.googleusercontent.com',
    iosClientId: '836951260412-35v72ncp1q4ejile0s4brlu4cq3lunsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.uwords',
  );
}
